---
kind: Pod
apiVersion: v1
metadata:
  name: pod04
spec:
  containers:
    - name: centos
      image: centos:7
      command:
        - "sleep"
        - "1000"

    - name: nginx
      image: nginx
      env:
        - name: MONGO_DB
          value: mongo
        - name: MONGODB_USR
          valueFrom:
            configMapKeyRef:
              key: MONGODB_USR
              name: MONGODB_USR
---
kind: ConfigMap
apiVersion: v1
metadata:
  name: MONGODB_USR
data:
  MONGODB_USR: root
