---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: payment
  labels:
    app: payment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: payment
  template:
    metadata:
      labels:
        app: payment
    spec:
      containers:
        - name: payment
          image: chandralekhas/d46-payment:v1
          env:
            - name: RABBITMQ_HOST
              value: rabbitmq
            - name: CART_HOST
              value: cart
            - name: USER_HOST
              value: user
            - name: RUSERNAME
              value: roboshop
            - name: RPASSWORD
              value: roboshop123
          ports:
            - containerPort: 7002
---
apiVersion: v1
kind: Service
metadata:
  name: payment
spec:
  selector:
    app: payment
  ports:
    - protocol: TCP
      port: 7002
      targetPort: 7002