apiVersion: storage.k8s.io/v1
kind: StorageClass
metadata:
  name:  aws-xfs
  annotations:
    storageclass.kubernetes.io/is-default-class: "true"
parameters:
  type: gp2
  fstype: xfs
provisioner: kubernetes.io/aws-ebs
reclaimPolicy: Delete
volumeBindingMode: WaitForFirstConsumer


