---
apiVersion: v1
kind: Namespace
metadata:
  name: user
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: user
  labels:
    app: user
spec:
  replicas: 1
  selector:
    matchLabels:
      app: user
  template:
    metadata:
      labels:
        app: user
    spec:
      containers:
        - name: user
          image: chandralekhas/d46-user:v1
          imagePullPolicy: Always
          env:
            - name: REDIS_HOST
              value: redis.redis.svc.cluster.local
            - name: MONGO_URL
              value: mongodb://mongodb.mongodb.svc.cluster.local:27017/users
          ports:
            - containerPort: 7007
---
apiVersion: v1
kind: Service
metadata:
  name: user
spec:
  selector:
    app: user
  ports:
    - protocol: TCP
      port: 7007
      targetPort: 7007